apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "n8n.fullname" . }}-netpol
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  
  policyTypes:
  - Ingress
  - Egress
  
  ingress:
  # Только Ingress Controller из tenant-root может обращаться к N8N
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tenant-root
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 5678
  
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

