apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: {{ .Values.tenant.name | default .Values.clientId }}
  namespace: {{ .Values.tenant.parentNamespace | default "tenant-root" }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  seaweedfs: {{ .Values.tenant.seaweedfs | default false }}
  etcd: {{ .Values.tenant.etcd | default false }}
  host: {{ .Values.tenant.host | default "" | quote }}
  ingress: {{ .Values.tenant.ingress | default false }}
  isolated: {{ .Values.tenant.isolated | default true }}
  monitoring: {{ .Values.tenant.monitoring | default false }}

