apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "n8n.fullname" . }}-wait-tenant
  namespace: default
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "n8n.fullname" . }}-wait-tenant
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: wait
        image: bitnami/kubectl:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/bash
        - -c
        - |
          echo "Ожидаем готовности Tenant {{ include "n8n.tenantName" . }}..."
          kubectl wait --for=condition=ready tenant {{ include "n8n.tenantName" . }} \
            --namespace {{ .Values.tenant.parentNamespace | default "tenant-root" }} \
            --timeout=300s
          echo "Tenant готов, продолжаем установку..."
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-wait-tenant
  namespace: default
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "n8n.fullname" . }}-wait-tenant
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["apps.cozystack.io"]
  resources: ["tenants"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "n8n.fullname" . }}-wait-tenant
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "n8n.fullname" . }}-wait-tenant
subjects:
- kind: ServiceAccount
  name: {{ include "n8n.fullname" . }}-wait-tenant
  namespace: default

