apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "n8n.fullname" . }}-wait-namespace
  namespace: default
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "n8n.fullname" . }}-wait-namespace
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: wait-namespace
        image: bitnami/kubectl:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for namespace {{ include "n8n.namespace" . }}..."
          for i in $(seq 1 30); do
            if kubectl get namespace {{ include "n8n.namespace" . }} >/dev/null 2>&1; then
              echo "Namespace {{ include "n8n.namespace" . }} found!"
              exit 0
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          echo "ERROR: Namespace {{ include "n8n.namespace" . }} not found after 60 seconds"
          exit 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-wait-namespace
  namespace: default
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "n8n.fullname" . }}-wait-namespace
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "n8n.fullname" . }}-wait-namespace
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "n8n.fullname" . }}-wait-namespace
subjects:
- kind: ServiceAccount
  name: {{ include "n8n.fullname" . }}-wait-namespace
  namespace: default

