apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-config
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  client-id: {{ .Values.clientId | quote }}
  domain: {{ .Values.domain | quote }}
